version: "3"

services:
 hsl-sl:
  container_name: hsl-sl
  image: infracloud/hsl-withsl:v1
  ports:
   - 8081:8081
  networks:
    vpcbr:
      ipv4_address: 10.5.0.5

 vloadgenerator:
  container_name: vloadgenerator
  image: infracloud/vloadgenerator:v1
  command: 'attack -u http://hsl-sl:8081 -n ${FREQUENCY} -d ${DURATION}'
  depends_on:
   - hsl-sl
  volumes:
    - /tmp:/app/report
  networks:
    vpcbr:
      ipv4_address: 10.5.0.6    

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         #gateway: 10.5.0.1